# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "I am provisioning..."
apt-get update && apt-get install -y default-jre
curl -O http://apache.mirrors.tds.net/tomcat/tomcat-7/v7.0.62/bin/apache-tomcat-7.0.62.tar.gz
tar zxvf apache-tomcat-7.*.tar.gz 
cd apache-tomcat-7.*
TC=`pwd`
cd $TC/webapps
wget http://repo1.maven.org/maven2/org/jolokia/jolokia-war/1.2.3/jolokia-war-1.2.3.war
mv jolokia-war-1.2.3.war jolokia.war
$TC/bin/catalina.sh start
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.ssh.forward_agent = true

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu_docker"

  config.vm.provider "virtualbox" do |v|
    v.name = "cluster_node2"
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "find proxyconf plugin !"
    if ENV["http_proxy"]
      puts "Settting the VM http_proxy to: " + ENV["http_proxy"]
      config.proxy.http     = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "Settting the VM https_proxy to: " + ENV["https_proxy"]
      config.proxy.https    = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      puts "Setting the VM no_proxy to: " + ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa_no_passphrase", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa_no_passphrase.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"

  config.vm.network :forwarded_port, guest: 8080, host: 10080

  config.vm.provision "shell", inline: $script

  config.vm.network "private_network", ip: "192.168.50.42"

end
