# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
#Docker 1.5 has a problem with the GE proxy. Its a known issue on their github
##Hence back off from v1.5 to v1.4.1
apt-get update
apt-get remove lxc-docker
apt-get install -y lxc-docker-1.4.1
apt-get install -y default-jre
#https://docs.docker.com/swarm/
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.ssh.forward_agent = true

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu_docker"

  config.vm.provider "virtualbox" do |v|
    v.name = "cluster_master"
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "find proxyconf plugin !"
    if ENV["http_proxy"]
      puts "Settting the VM http_proxy to: " + ENV["http_proxy"]
      config.proxy.http     = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "Settting the VM https_proxy to: " + ENV["https_proxy"]
      config.proxy.https    = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      puts "Setting the VM no_proxy to: " + ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa_no_passphrase", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa_no_passphrase.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"

  config.vm.network :forwarded_port, guest: 9200, host: 9201
  config.vm.network :forwarded_port, guest: 5601, host: 5602

  config.vm.network "private_network", ip: "192.168.50.40"

  config.vm.provision "shell", inline: $script

end
